export const moviesMock = [
  {
    id: 203,
    year: '2019',
    title: 'Cats',
    studios: 'Universal Pictures',
    producers: 'Debra Hayward, Tim Bevan, Eric Fellner, and Tom Hooper',
    winner: 'yes',
  },
  {
    id: 206,
    year: '2019',
    title: 'A Madea Family Funeral',
    studios: 'Lionsgate',
    producers: 'Ozzie Areu, Will Areu, and Mark E. Swinton',
    winner: '',
  },
  {
    id: 207,
    year: '2019',
    title: 'Rambo: Last Blood',
    studios: 'Lionsgate',
    producers: 'Avi Lerner, Kevin King Templeton, Yariv Lerner, and Les Weldon',
    winner: '',
  },
  {
    id: 182,
    year: '2015',
    title: 'Fantastic Four',
    studios: '20th Century Fox',
    producers:
      'Simon Kinberg, Matthew Vaughn, Hutch Parker, Robert Kulzer and Gregory Goodman',
    winner: 'yes',
  },
  {
    id: 183,
    year: '2015',
    title: 'Fifty Shades of Grey',
    studios: 'Universal Pictures, Focus Features',
    producers: 'Michael De Luca, Dana Brunetti and E. L. James',
    winner: 'yes',
  },
  {
    id: 184,
    year: '2015',
    title: 'Jupiter Ascending',
    studios: 'Warner Bros.',
    producers: 'Grant Hill and The Wachowskis',
    winner: '',
  },
  {
    id: 185,
    year: '2015',
    title: 'Paul Blart: Mall Cop 2',
    studios: 'Columbia Pictures',
    producers: 'Todd Garner, Kevin James and Adam Sandler',
    winner: '',
  },
  {
    id: 186,
    year: '2015',
    title: 'Pixels',
    studios: 'Columbia Pictures',
    producers: 'Adam Sandler, Chris Columbus, Mark Radcliffe and Allen Covert',
    winner: '',
  },
];

export const winnerMovies = [
  {
    id: 2,
    year: '1980',
    title: "Can't Stop the Music",
    studios: 'Associated Film Distribution',
    producers: 'Allan Carr',
    winner: 'yes',
  },
  {
    id: 12,
    year: '1981',
    title: 'Mommie Dearest',
    studios: 'Paramount Pictures',
    producers: 'Frank Yablans',
    winner: 'yes',
  },
  {
    id: 17,
    year: '1982',
    title: 'Inchon',
    studios: 'MGM',
    producers: 'Mitsuharu Ishii',
    winner: 'yes',
  },
  {
    id: 22,
    year: '1983',
    title: 'The Lonely Lady',
    studios: 'Universal Studios',
    producers: 'Robert R. Weston',
    winner: 'yes',
  },
  {
    id: 27,
    year: '1984',
    title: 'Bolero',
    studios: 'Cannon Films',
    producers: 'Bo Derek',
    winner: 'yes',
  },
  {
    id: 32,
    year: '1985',
    title: 'Rambo: First Blood Part II',
    studios: 'Columbia Pictures',
    producers: 'Buzz Feitshans',
    winner: 'yes',
  },
  {
    id: 37,
    year: '1986',
    title: 'Howard the Duck',
    studios: 'Universal Studios',
    producers: 'Gloria Katz',
    winner: 'yes',
  },
  {
    id: 38,
    year: '1986',
    title: 'Under the Cherry Moon',
    studios: 'Warner Bros.',
    producers: 'Bob Cavallo, Joe Ruffalo and Steve Fargnoli',
    winner: 'yes',
  },
  {
    id: 42,
    year: '1987',
    title: 'Leonard Part 6',
    studios: 'Columbia Pictures',
    producers: 'Bill Cosby',
    winner: 'yes',
  },
  {
    id: 47,
    year: '1988',
    title: 'Cocktail',
    studios: 'Touchstone Pictures',
    producers: 'Ted Field and Robert W. Cort',
    winner: 'yes',
  },
  {
    id: 52,
    year: '1989',
    title: 'Star Trek V: The Final Frontier',
    studios: 'Paramount Pictures',
    producers: 'Harve Bennett',
    winner: 'yes',
  },
  {
    id: 57,
    year: '1990',
    title: 'The Adventures of Ford Fairlane',
    studios: '20th Century Fox',
    producers: 'Steven Perry and Joel Silver',
    winner: 'yes',
  },
  {
    id: 58,
    year: '1990',
    title: "Ghosts Can't Do It",
    studios: 'Triumph Releasing',
    producers: 'Bo Derek',
    winner: 'yes',
  },
  {
    id: 62,
    year: '1991',
    title: 'Hudson Hawk',
    studios: 'TriStar Pictures',
    producers: 'Joel Silver',
    winner: 'yes',
  },
  {
    id: 67,
    year: '1992',
    title: 'Shining Through',
    studios: '20th Century Fox',
    producers: 'Carol Baum and Howard Rosenman',
    winner: 'yes',
  },
  {
    id: 72,
    year: '1993',
    title: 'Indecent Proposal',
    studios: 'Paramount Pictures',
    producers: 'Sherry Lansing',
    winner: 'yes',
  },
  {
    id: 77,
    year: '1994',
    title: 'Color of Night',
    studios: 'Hollywood Pictures',
    producers: 'Buzz Feitshans and David Matalon',
    winner: 'yes',
  },
  {
    id: 82,
    year: '1995',
    title: 'Showgirls',
    studios: 'MGM, United Artists',
    producers: 'Charles Evans and Alan Marshall',
    winner: 'yes',
  },
  {
    id: 87,
    year: '1996',
    title: 'Striptease',
    studios: 'Columbia Pictures, Castle Rock Entertainment',
    producers: 'Andrew Bergman and Mike Lobell',
    winner: 'yes',
  },
  {
    id: 92,
    year: '1997',
    title: 'The Postman',
    studios: 'Warner Bros.',
    producers: 'Kevin Costner, Steve Tisch and Jim Wilson',
    winner: 'yes',
  },
  {
    id: 97,
    year: '1998',
    title: 'An Alan Smithee Film: Burn Hollywood Burn',
    studios: 'Hollywood Pictures',
    producers: 'Ben Myron and Joe Eszterhas',
    winner: 'yes',
  },
  {
    id: 102,
    year: '1999',
    title: 'Wild Wild West',
    studios: 'Warner Bros.',
    producers: 'Jon Peters and Barry Sonnenfeld',
    winner: 'yes',
  },
  {
    id: 107,
    year: '2000',
    title: 'Battlefield Earth',
    studios: 'Warner Bros., Franchise Pictures',
    producers: 'Jonathan D. Krane, Elie Samaha and John Travolta',
    winner: 'yes',
  },
  {
    id: 112,
    year: '2001',
    title: 'Freddy Got Fingered',
    studios: '20th Century Fox',
    producers: 'Larry Brezner, Howard Lapides and Lauren Lloyd',
    winner: 'yes',
  },
  {
    id: 117,
    year: '2002',
    title: 'Swept Away',
    studios: 'Screen Gems',
    producers: 'Matthew Vaughn',
    winner: 'yes',
  },
  {
    id: 122,
    year: '2003',
    title: 'Gigli',
    studios: 'Columbia Pictures, Revolution Studios',
    producers: 'Martin Brest and Casey Silver',
    winner: 'yes',
  },
  {
    id: 127,
    year: '2004',
    title: 'Catwoman',
    studios: 'Warner Bros.',
    producers: 'Denise Di Novi and Edward McDonnell',
    winner: 'yes',
  },
  {
    id: 132,
    year: '2005',
    title: 'Dirty Love',
    studios: 'First Look Pictures',
    producers:
      'John Mallory Asher, BJ Davis, Rod Hamilton, Kimberley Kates, Michael Manasseri, Jenny McCarthy and Trent Walford',
    winner: 'yes',
  },
  {
    id: 137,
    year: '2006',
    title: 'Basic Instinct 2',
    studios: 'MGM, C2 Pictures',
    producers: 'Mario Kassar, Joel B. Michaels and Andrew G. Vajna',
    winner: 'yes',
  },
  {
    id: 147,
    year: '2008',
    title: 'The Love Guru',
    studios: 'Paramount Pictures',
    producers: 'Gary Barber, Michael DeLuca and Mike Myers',
    winner: 'yes',
  },
  {
    id: 152,
    year: '2009',
    title: 'Transformers: Revenge of the Fallen',
    studios: 'Paramount Pictures, DreamWorks, Hasbro',
    producers: 'Lorenzo di Bonaventura, Ian Bryce, Tom DeSanto and Don Murphy',
    winner: 'yes',
  },
  {
    id: 157,
    year: '2010',
    title: 'The Last Airbender',
    studios: 'Paramount Pictures, Nickelodeon Movies',
    producers:
      'Frank Marshall, Kathleen Kennedy, Sam Mercer and M. Night Shyamalan',
    winner: 'yes',
  },
  {
    id: 162,
    year: '2011',
    title: 'Jack and Jill',
    studios: 'Columbia Pictures',
    producers: 'Todd Garner, Jack Giarraputo and Adam Sandler',
    winner: 'yes',
  },
  {
    id: 167,
    year: '2012',
    title: 'The Twilight Saga: Breaking Dawn – Part 2',
    studios: 'Summit Entertainment',
    producers: 'Wyck Godfrey, Stephenie Meyer and Karen Rosenfelt',
    winner: 'yes',
  },
  {
    id: 172,
    year: '2013',
    title: 'Movie 43',
    studios: 'Relativity Media',
    producers:
      'Peter Farrelly, Ryan Kavanaugh, John Penotti and Charles B. Wessler',
    winner: 'yes',
  },
  {
    id: 177,
    year: '2014',
    title: 'Saving Christmas',
    studios: 'Samuel Goldwyn Films',
    producers: 'Darren Doane, Raphi Henley, Amanda Rosser and David Shannon',
    winner: 'yes',
  },
  {
    id: 182,
    year: '2015',
    title: 'Fantastic Four',
    studios: '20th Century Fox',
    producers:
      'Simon Kinberg, Matthew Vaughn, Hutch Parker, Robert Kulzer and Gregory Goodman',
    winner: 'yes',
  },
  {
    id: 183,
    year: '2015',
    title: 'Fifty Shades of Grey',
    studios: 'Universal Pictures, Focus Features',
    producers: 'Michael De Luca, Dana Brunetti and E. L. James',
    winner: 'yes',
  },
  {
    id: 187,
    year: '2016',
    title: "Hillary's America: The Secret History of the Democratic Party",
    studios: 'Quality Flix',
    producers: 'Gerald R. Molen',
    winner: 'yes',
  },
  {
    id: 193,
    year: '2017',
    title: 'The Emoji Movie',
    studios: 'Columbia Pictures',
    producers: 'Michelle Raimo Kouyate',
    winner: 'yes',
  },
  {
    id: 198,
    year: '2018',
    title: 'Holmes & Watson',
    studios: 'Columbia Pictures',
    producers: 'Will Ferrell, Adam McKay, Jimmy Miller and Clayton Townsend',
    winner: 'yes',
  },
  {
    id: 203,
    year: '2019',
    title: 'Cats',
    studios: 'Universal Pictures',
    producers: 'Debra Hayward, Tim Bevan, Eric Fellner, and Tom Hooper',
    winner: 'yes',
  },
];
